allowBuilds:
  "@swc/core": true
  esbuild: true
  "eslint-plugin-lensflow@https://codeload.github.com/alexeieleusis/lens-flow/tar.gz/0c326d9e96dde638a66f593ca763290a8e383418#path:/eslint-lensflow-plugin": true
