allowBuilds:
  "@swc/core": true
  esbuild: true
  "eslint-plugin-lensflow@https://codeload.github.com/alexeieleusis/lens-flow/tar.gz/93423eacb7af2b8d3a15e55670abd4d709bdb031#path:/eslint-lensflow-plugin": true
