allowBuilds:
  "@swc/core": true
  esbuild: true
  "eslint-plugin-lensflow@https://codeload.github.com/alexeieleusis/lens-flow/tar.gz/efa1152c4e1f625f7f8ae162538c0011c2482ffd#path:/eslint-lensflow-plugin": true
